
server:
  host: "0.0.0.0"
  port: 8321
  endpoint: "/infer"

model:
  adapter: "openpi_rtc_triton"
  config_name: "pi05_droid"
  checkpoint: "../../weights/realtime_vla/pi05_base_converted.pkl" # 统一权重目录；原为上游机器的 pi05_droid_finetune 微调权重，本地目前仅有 base 转换权重
  prompt: "Pick up the bottle."
  adarms_knob: 0
  valid_action_num: 15 # 15
  action_horizon: 15 # 15
  action_type: "joint"
  image_size: [640, 480]
  tokenizer_path: "/home/liguopu/lgp_dev/project/realtime-vla/paligemma-3b-pt-224"
  norm_stats_dir: "/home/liguopu/lgp_dev/project/openpi/checkpoints/pi05_droid_finetune_low_mem/my_experiment/1999/assets/droid"
  discrete_state_input: true
  state_dim: 14
  action_dim: 14
  noise_seed: null

inference:
  optimizer: "timeaxis_smooth"
  timeaxis_dt_ref_s: 0.01
  timeaxis_dt_min_s: 0.008
  timeaxis_dt_max_s: 0.016
  timeaxis_lambda_acc: 10.0
  timeaxis_lambda_time: 1.0
  timeaxis_stride: 15
  timeaxis_optdims: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  timeaxis_v_max: null
  timeaxis_lambda_v: 10.0
  timeaxis_horizon: 15 # 15
  timeaxis_logging: false


